php:
  build: .
  links:
    - db
  volumes:
    - .:/var/www/docker-symfony
nginx:
  image: nginx:1.9.9
  links:
    - php
  volumes_from:
    - php
  volumes:
    - ./docker/vhost.conf:/etc/nginx/conf.d/default.conf
  ports:
    - "80:80"
db:
  image: mongo:3.2.0
  volumes:
    - /mnt/sda1/var/lib/mongo-data:/data/db
  ports:
    - "27017:27017"
