web:
  build: .
  links:
    - db
  environment:
    APACHE_LOG_DIR: /var/log/apache2
  volumes:
    - .:/var/www/docker-symfony
  ports:
    - "80:80"
db:
  image: mongo:latest
  volumes:
    - /mnt/sda1/var/lib/mongo-data:/data/db
  ports:
    - "27017:27017"
